### ISSUE TITLE
Parameters-Tuning.rst

### ISSUE THREAD

**Issue by rickiepark** [Pseudo-Lab/lightgbm-docs#12]

**Comment by jeongminju0815** [comment]
이 부분 번역 맡아보고 싶습니다 :)

**Comment by rickiepark** [comment]
@jeongminju0815 님, 번역 작업이 어떻게 진행되고 있는지 피드백 부탁드립니다! :)

**Comment by jeongminju0815** [comment]
안녕하세요!
아직 작업 중인데, 혹시 언제까지 마무리하면 될까요?
작업 늦어진점 죄송합니다 ㅠㅠ!





2023년 6월 2일 (금) 오전 11:12, Haesun Park ***@***.***>님이 작성:

**Comment by rickiepark** [comment]
저희가 6월 14일에 회의를 진행하기로 했습니다. 혹시 그 전까지 작업이 가능하실까요? :)

**Comment by jeongminju0815** [comment]
네! 회의 전까지 작업 완료하겠습니다 :)




2023년 6월 2일 (금) 오후 9:07, Haesun Park ***@***.***>님이 작성:

**Comment by rickiepark** [comment]
PR 머지되어 이슈 종결합니다!
